### ISSUE TITLE
Use in-app ratings API

### ISSUE THREAD

**Issue by rajkumaar23** [amrita-repository/android-app#72]
https://android-developers.googleblog.com/2020/08/in-app-review-api.html?m=1

**Comment by swayangjit** [comment]
@rajkumaar23  Can you specify where you want to show the in app rating popup?

**Comment by rajkumaar23** [comment]
So, there are 2 places this popup is required
- https://github.com/amrita-repository/android-app/blob/f32e8f64e5c1e5ffcc05e541bb1fc839348ab49c/app/src/main/java/in/co/rajkumaar/amritarepo/activities/LaunchingActivity.java#L478
- And when AboutActivity is opened, pop this up.

In both cases, ensure that this popup doesn't come after the user has submitted the review once. 
In the side navbar, you can use the existing behaviour (redirect to store) **in case** the review is already submitted.

Let me know if you have any more queries :)
