### ISSUE TITLE
Upgrade AUMS Lite module

### ISSUE THREAD

**Issue by rajkumaar23** [amrita-repository/android-app#78]

**Comment by ColdCoffee21** [comment]
cb.en.u4cse18069@cb.students.amrita.edu

**Comment by radiantly** [comment]
Correct me if I'm wrong, but the `/DataServices/rest/` path no longer seems to work even after swapping with the new subdomain. This might mean that we may have to wait for the app to be updated before we can upgrade the Lite version.

**Comment by rajkumaar23** [comment]
Do you mean the error regarding TLS handshake fail ? 
The new subdomain has TLS configured improperly and thus browsers/HTTP clients will not make the connection. https://www.sslshopper.com/ssl-checker.html#hostname=https://aumscb.amrita.edu

I have informed the team regarding this. We’ll have to wait until they fix the certificate. 

Or do you face any other issue?

**Comment by radiantly** [comment]
I noticed the certificate error but ignoring that, `https://aumscb.amrita.edu/DataServices/rest/authRes` and similar paths return a 500 internal server error.

**Comment by rajkumaar23** [comment]
Ah right. We'll have to wait until the 500 is resolved.
