### ISSUE TITLE
Create new files instead of overwriting incase of duplicates

### ISSUE THREAD

**Issue by deebakkarthi** [amrita-repository/android-app#83]
When downloading a question paper, if there is already a file with the same name, it gets overwritten. It would be better if a new file was created with a suffix like ```CSE330_(1).pdf```.
This will be very useful as question papers of multiple years have the same name.

**Comment by rajkumaar23** [comment]
@deebakkarthi  I am not actively contributing to this anymore. If you would like to go ahead and fix this issue, I would be happy to review and merge.

**Comment by rajkumaar23** [comment]
there you go @deebakkarthi! the feature is merged.
